export const NATIVE_PLUGINS = [
  "Fruity Parametric EQ 2",
  "Fruity Limiter",
  "Fruity Compressor",
  "Maximus",
  "Fruity Reeverb 2",
  "Fruity Delay 3",
  "Fruity Soft Clipper",
  "Soundgoodizer",
  "Stereo Shaper",
  "Edison",
  "Wave Candy",
  "Patcher",
  "Pitcher",
  "Gross Beat",
  "FLEX",
  "Sytrus",
  "Harmor",
  "Harmless",
  "Sakura",
  "NewTone",
  "Slicex",
] as const;

export const THIRD_PARTY_BRANDS = [
  "FabFilter",
  "Waves",
  "iZotope",
  "Antares",
  "Melodyne",
  "Soundtoys",
  "Valhalla",
  "SSL",
  "Plugin Alliance",
  "Slate Digital",
  "UAD",
  "Eventide",
  "Auto-Tune",
  "Ozone",
  "Neutron",
  "Other",
] as const;
